config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'desks#index'
  resources :desks do
    resources :bookings, only: [:create, :new]
  end

  resources :bookings, except: [:create, :new]
  get "my_bookings", to:"bookings#my_bookings"
  get "my_desks", to:"desks#my_desks"

  # For further details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :desk
  belongs_to :user # only for renter

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/desk.rb
class Desk < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user

  validates :price, presence: true, allow_blank: false
  validates :location, presence: true, allow_blank: false
  validates :seats, presence: true, allow_blank: false
  validates :title, presence: true, allow_blank: false
  validates :start_date, presence: true
  validates :end_date, presence: true

  has_one_attached :photo
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model

  pg_search_scope :search_by_title_location,
    against: [ :title, :location ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :desks
  has_many :bookings
  has_many :bookings_as_owner, through: :desks, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    # @bookings = Booking.all
    @my_bookings = current_user.bookings
    @bookings_as_owner = current_user.bookings_as_owner
  end

  def show
  end

  def new
    @desk = Desk.find(params[:desk_id])
    @booking = Booking.new
  end

  def edit
  end

  def create
    @desk = Desk.find(params[:desk_id])
    @booking = Booking.new(booking_params)
    @booking.desk = @desk
    @booking.user = current_user

    if @booking.save!
      redirect_to @booking, notice: 'A booking was successfully created.'

    else
      render :new
    end
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'booking was successfully updated.'
    else
      render :edit
    end
  end

  def my_bookings
    @bookings = current_user.bookings
  end

  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'booking was successfully destroyed.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/desks_controller.rb
class DesksController < ApplicationController
  before_action :set_desk, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :index]

  def index
    @user = current_user
    if params[:query].present?
      @desks = Desk.search_by_title_location(params[:query]).order(updated_at: :desc)
    else
      @desks = Desk.all.order(updated_at: :desc)
    end
    @markers = @desks.geocoded.map do |desk|
      {
        lat: desk.latitude,
        lng: desk.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { desk: desk }),
        image_url: helpers.asset_url('laptop.svg')
      }
    end
  end

  def show
  end

  def new
    @desk = Desk.new
  end

  def edit
  end

  def create
    @desk = Desk.new(desk_params)
    @desk.user = current_user

    if @desk.save
      redirect_to @desk, notice: 'A desk was successfully created.'
    else
      render :new
    end
  end

  def update
    if @desk.update(desk_params)
      redirect_to @desk, notice: 'Desk was successfully updated.'
    else
      render :edit
    end
  end

  def my_desks
    currentuser.desks
  end

  def destroy
    @desk.destroy
    redirect_to desks_url, notice: 'Desk was successfully destroyed.'
  end

  private

  def set_desk
    @desk = Desk.find(params[:id])
  end

  def desk_params
    params.require(:desk).permit(:title, :price, :location, :seats, :start_date, :end_date, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<!-- name of my desk, start_date, end-date of availability  -->
  <div class="container">
    <br>
    <br>
  <h2>Desks i'll be working from!</h2>
  <br>
  <div class="cards">
    <% @my_bookings.each do |booking| %>
    <% if booking.desk.photo.attached? %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
      url('<%= cl_image_path booking.desk.photo.key %>')">
      <% else %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
             url('https://source.unsplash.com/weekly?desk')">
      <% end %>
              <p class="pl-4"><%= link_to booking.desk.title, booking_path(booking), class:"booking-title" %></p>
        <%= link_to booking_path(booking), method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="fas fa-trash-alt" id="cards"></i>
        <% end %>
      </div>
    <% end %>
  </div>

<!-- my bookings for desks i rented out -->

  <h2>Desks I rented out!</h2>
    <br>
    <div class="cards">
      <% @bookings_as_owner.each do |booking| %>
      <% if booking.desk.photo.attached? %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
        url('<%= cl_image_path booking.desk.photo.key %>')">
        <% else %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
               url('https://source.unsplash.com/weekly?desk')">
        <% end %>
                <p class="pl-4"><%= link_to booking.desk.title, booking_path(booking), class:"booking-title" %></p>
          <%= link_to booking_path(booking), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fas fa-trash-alt" id="cards"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/bookings/new.html.erb
<!-- link to the bookings#indexpage in the navbar. -->
<div class="container pt-5">
  <div class="row justify-content-center">
    <div id="make_booking_column" class="col-12">
      <!-- link to the bookings#indexpage in the navbar. -->
      <div class="col-md-12">
        <h1>Make a Reservation</h1>
        <%= simple_form_for [@desk, @booking] do |f| %>
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.button :submit, class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>

app/views/bookings/show.html.erb
<div id="show-desk-container" class="show-container">
  <div class="show-row">
    <div class="col-sm">


      <div class="show-card">
        <div class="show-image"></div>
         <% if @booking.desk.photo.attached? %>
             <%= cl_image_tag(@booking.desk.photo.key,
        width: 750, height: 400, crop: :fill) %>
         <% else %>
            <%= image_tag 'Placeholder_image', class: 'placeholder'%>
        <% end %>

        <div class="show-text">
          <div class="show-border">
           <h2 class="show-desk-title"><%= @booking.desk.title %></h2>
            <h3>€ -&#160;<%= @booking.desk.price %> /day</h3>
            <h4><em><i class="fas fa-map-marker-alt"></i> -&#160;<%= @booking.desk.location %></em></h4>
            <h4><i class="fas fa-chair"></i> -&#160;<%= pluralize @booking.desk.seats, "seat" %></h4>
          </div>
          <h5 id="p">Booked <%= @booking.desk.start_date.strftime("%m/%d/%y") %> to <%= @booking.desk.end_date.strftime("%m/%d/%y") %></h5
        </div>
      </div>
        </div>
  </div>
</div>

app/views/desks/_info_window.html.erb
<h2><%= link_to desk.title, desk_path(desk), class:"link-to-card-product-1 no-hover-link" %></h2>
<p><%= desk.location %></p>

app/views/desks/edit.html.erb
<div class="container pt-5">
  <div class="row justify-content-center">
    <div id="edit_desk_column" class="col-12">
      <div class="col-md-12">
        <h1>Update Desk</h1>

        <%= simple_form_for @desk do |f| %>
        <%= f.input :title %>
        <%= f.input :seats %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.input :location %>
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.button :submit, class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>

app/views/desks/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.pinimg.com/originals/17/5e/da/175eda03beec29af20dfc40a38e5ac68.jpg);">


  <div class="container-banner">
    <h1>air<strong>BRB</strong></h1>
    <div class="form-group row" id="search">
        <%= form_tag desks_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a desk near you..."
        %>
        <%= submit_tag "Search", class: "btn btn-success", id: "search1"%>
      <% end %>
    </div>

  </div>
</div>

<div class="row">

  <div class="col-8">
  <% @desks.each do |desk| %>
  <%= link_to desk_path(desk), class:"no-hover-link" do%>
  <div class="card-product">
    <% if desk.photo.attached? %>
    <%= cl_image_tag(desk.photo.key) %>
    <% else %>
    <%= image_tag "Placeholder_image"%>
    <% end %>
    <div class="card-product-infos">
      <h3 class="card-desk-title"><%=  desk.title %></h3>
      <br>
      <h4 class="card-desk-text">€ -&#160;<strong><%= desk.price %> </strong>/day</></h4>

      <h4 class="card-desk-text"><i class="fas fa-map-marker-alt"></i> -&#160;<%= desk.location%></h4>

      <h4 class="card-desk-text"><i class="fas fa-chair"> -&#160; </i><%= pluralize desk.seats, "seat" %> </h4>
    </div>
  </div>

  <% end %>
  <% end %>
  </div>

<div class="col-4">
    <div id="map"
    style="width: 100%; height: 100vh;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>



<script>

var map = new mapboxgl.Map({
  container: 'map',
  style: 'mapbox://styles/mapbox/light-v10',
  center: [-96, 37.8],
  zoom: 3
});


</script>
</div>

app/views/desks/new.html.erb
<div class="container pt-5">
  <div class="row justify-content-center">
    <div id="column" class="col-12">
      <div class="col-md-12">
        <h1>Create a new Desk</h1>
        <%= simple_form_for @desk do |f| %>
        <%= f.input :title %>
        <%= f.input :seats %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.input :location %>
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.button :submit, class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>

app/views/desks/show.html.erb
<div id="show-desk-container" class="show-container">
  <div class="show-row">
    <div class="col-sm">


      <div class="show-card">
        <div class="show-image"></div>
         <% if @desk.photo.attached? %>
             <%= cl_image_tag(@desk.photo.key,
        width: 750, height: 400, crop: :fill) %>
         <% else %>
            <%= image_tag 'Placeholder_image', class: 'placeholder'%>
        <% end %>

        <div class="show-text">
          <div class="show-border">
           <h2 class="show-desk-title"><%= @desk.title %></h2>
            <h3>€ -&#160;<%= @desk.price %> per day</h3>
            <h4><em><i class="fas fa-map-marker-alt"></i> -&#160;<%= @desk.location %></em></h4>
            <h4><i class="fas fa-chair"></i> -&#160;<%= pluralize @desk.seats, "seat" %></h4>
          </div>
          <h5 id="p">Available from <%= @desk.start_date.strftime("%m/%d/%y") %> to <%= @desk.end_date.strftime("%m/%d/%y") %></h5>
        </div>
      </div>
        </div>
      <div class="show-buttons">

      <button class="btn btn-success"> <%= link_to "Back to all desks", root_path %></button>
      <button class="btn btn-success"><%= link_to "Edit desk", edit_desk_path %></button>
      <% user = User.find(@desk.user_id) %>
      <% if user != current_user %>
      <button class="btn btn-success"> <%= link_to 'Book this desk!', new_desk_booking_path(@desk) %></button>
      <% end %>

      </div>
    </div>
  </div>
<!--     <div class="col-sm">
        <div id="map"
    style="width: 100%; height: 500px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div> -->
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AIRBRB</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap" rel="stylesheet">
  </head>
  <body style="margin: 0;">
    <%= render 'shared/navbar' %>
    <div class="container-king">
    <%= yield %>
  </div>
    <%= render 'shared/footer' %>
  </body>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/index.html.erb
<h1>placeholder for index?</h1>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-copyright">
    Be Right Back!
    <%= image_tag "logo.png", alt: "AirBrB", size: "50x50" %>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to(image_tag("nav_logo.png", size: "50x50"), desks_path) %>
  <ul class="ul-navbar">
    <li class="li-navbar"><%= link_to 'add a desk', new_desk_path%></li>
    <li class="li-navbar"><%= link_to 'explore', desks_path%></li>
    <% if current_user %>
      <li class="li-navbar"><%= link_to 'my bookings', bookings_path %></li>
      <li class="li-navbar"><%= link_to 'sign out', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li class="li-navbar"><%= link_to 'sign up', new_user_registration_path%></li>
      <li class="li-navbar"><%= link_to 'login', new_user_session_path%></li>
    <% end %>
  </ul>
</div>